/ CREATE MEMBER TABLE /
CREATE TABLE MEMBER(
MB_ID NVARCHAR2(20) NOT NULL,
MB_SIRSISCODE NCHAR(10) NOT NULL,
MB_NICK NVARCHAR2(10) NOT NULL,
MB_PW NVARCHAR2(2000) NOT NULL,
MB_NAME NVARCHAR2(10) NOT NULL,
MB_GENDER NCHAR(2) NOT NULL,
MB_BIRTHDAY NVARCHAR2(8) NOT NULL,
MB_ADDRESS NVARCHAR2(255) NOT NULL,
MB_EMAIL NVARCHAR2(40) NOT NULL,
MB_STCODE NCHAR(2) NOT NULL,
MB_SIRCODE NCHAR(5) NOT NULL,
MB_PHONENUMBER NCHAR(11) NOT NULL
)TABLESPACE smartInStudy;

/ CREATE SMART_IN_STUDY TABLE /
CREATE TABLE SMART_IN_STUDY(
SIS_CODE NCHAR(10) NOT NULL,
SIS_NAME NVARCHAR2(255) NOT NULL,
SIS_INTRO NVARCHAR2(2000) NOT NULL,
SIS_ADDRESS NVARCHAR2(255) NOT NULL,
SIS_IMG1 NVARCHAR2(255) NOT NULL,
SIS_IMG2 NVARCHAR2(255) NOT NULL,
SIS_IMG3 NVARCHAR2(255) NOT NULL,
SIS_IMG4 NVARCHAR2(255) NOT NULL,
SIS_NUMBER NVARCHAR2(22) NOT NULL,
SIS_PHONENUMBER NCHAR(11) NOT NULL
)TABLESPACE smartInStudy;

/ CREATE PAYMENT_HISTORY TABLE /
CREATE TABLE PAYMENT_HISTORY(
PH_ACCOUNTID NVARCHAR2(100) NOT NULL,
PH_SIRSISCODE NCHAR(10) NOT NULL,
PH_SIRCODE NCHAR(5) NOT NULL,
PH_MBID NVARCHAR2(20) NOT NULL,
PH_APPROVALNUMBER NVARCHAR2(100) NOT NULL,
PH_DATE DATE DEFAULT SYSDATE NOT NULL,
PH_ENDDATE DATE NOT NULL,
PH_PRICE NUMBER NOT NULL
)TABLESPACE smartInStudy;

/ CREATE GOALS_MEMBER TABLE /
CREATE TABLE GOALS_MEMBER(
GM_PHACCOUNTID NVARCHAR2(100) NOT NULL,
GM_PHSIRSISCODE NCHAR(10) NOT NULL,
GM_PHSIRCODE NCHAR(5) NOT NULL,
GM_PHMBID NVARCHAR2(20) NOT NULL,
GM_HIR NVARCHAR2(100) NOT NULL,
GM_RFID NVARCHAR2(100) NOT NULL
)TABLESPACE smartInStudy;

/ CREATE HISTORY TABLE /
CREATE TABLE HISTORY(
HI_MBSIRSISCODE NCHAR(10) NOT NULL,
HI_MBID NVARCHAR2(20) NOT NULL,
HI_DATE DATE DEFAULT SYSDATE NOT NULL,
HI_STCODE NCHAR(2) NOT NULL
)TABLESPACE smartInStudy;

/ CREATE STATUS TABLE /
CREATE TABLE STATUS(
ST_CODE NCHAR(2) NOT NULL,
ST_NAME NVARCHAR2(10) NOT NULL
)TABLESPACE smartInStudy;

/ CREATE SMART_IN_ROOM TABLE /
CREATE TABLE SMART_IN_ROOM(
SIR_SISCODE NCHAR(10) NOT NULL,
SIR_CODE NCHAR(5) NOT NULL,
SIR_NAME NVARCHAR2(50) NOT NULL
)TABLESPACE smartInStudy;

/ CREATE SENSOR TABLE /
CREATE TABLE LIGHT_SENSOR(
SE_SIRSISCODE NCHAR(10) NOT NULL,
SE_SIRCODE NCHAR(5) NOT NULL,
SE_CODE NVARCHAR2(22) NOT NULL,
SE_DATE DATE DEFAULT SYSDATE NOT NULL,
SE_DATA NVARCHAR2(100) NOT NULL
)TABLESPACE smartInStudy;

CREATE TABLE DHT_SENSOR(
SE_SIRSISCODE NCHAR(10) NOT NULL,
SE_SIRCODE NCHAR(5) NOT NULL,
SE_CODE NVARCHAR2(22) NOT NULL,
SE_DATE DATE DEFAULT SYSDATE NOT NULL,
SE_DATA NVARCHAR2(100) NOT NULL,
SE_DATA2 NVARCHAR2(100) NOT NULL
)TABLESPACE smartInStudy;

CREATE TABLE DUST_SENSOR(
SE_SIRSISCODE NCHAR(10) NOT NULL,
SE_SIRCODE NCHAR(5) NOT NULL,
SE_CODE NVARCHAR2(22) NOT NULL,
SE_DATE DATE DEFAULT SYSDATE NOT NULL,
SE_DATA NVARCHAR2(100) NOT NULL
)TABLESPACE smartInStudy;

CREATE TABLE RFID_SENSOR(
SE_SIRSISCODE NCHAR(10) NOT NULL,
SE_SIRCODE NCHAR(5) NOT NULL,
SE_CODE NVARCHAR2(22) NOT NULL,
SE_DATE DATE DEFAULT SYSDATE NOT NULL,
SE_DATA NVARCHAR2(100) NOT NULL,
SE_LOG NVARCHAR2(100) NOT NULL
)TABLESPACE smartInStudy;

CREATE TABLE HIR_SENSOR(
SE_SIRSISCODE NCHAR(10) NOT NULL,
SE_SIRCODE NCHAR(5) NOT NULL,
SE_CODE NVARCHAR2(22) NOT NULL,
SE_DATE DATE DEFAULT SYSDATE NOT NULL,
SE_DATA NVARCHAR2(100) NOT NULL
)TABLESPACE smartInStudy;

CREATE TABLE IR_SENSOR(
SE_SIRSISCODE NCHAR(10) NOT NULL,
SE_SIRCODE NCHAR(5) NOT NULL,
SE_CODE NVARCHAR2(22) NOT NULL,
SE_DATE DATE DEFAULT SYSDATE NOT NULL,
SE_DATA NVARCHAR2(100) NOT NULL
)TABLESPACE smartInStudy;

CREATE TABLE SOUND_SENSOR(
SE_SIRSISCODE NCHAR(10) NOT NULL,
SE_SIRCODE NCHAR(5) NOT NULL,
SE_CODE NVARCHAR2(22) NOT NULL,
SE_DATE DATE DEFAULT SYSDATE NOT NULL,
SE_DATA NVARCHAR2(100) NOT NULL
)TABLESPACE smartInStudy;

/CREATE REQUEST_SERVICE TABLE/
CREATE TABLE REQUEST_SERVICE(
RS_NAME NVARCHAR2(10) NOT NULL,
RS_PHONENUMBER NCHAR(11) NOT NULL,
RS_ADDRESS NVARCHAR2(255) NOT NULL,
RS_CONTENT NVARCHAR2(2000) NOT NULL,
RS_STCODE NCHAR(2) NOT NULL,
RS_SEQUENCE NUMBER NOT NULL
)TABLESPACE smartInStudy;

/ SET CONSTRAINT /
/ SET PRIMARY KEY /
ALTER TABLE MEMBER
ADD CONSTRAINT MB_PK PRIMARY KEY(MB_ID, MB_SIRSISCODE);

ALTER TABLE SMART_IN_STUDY
ADD CONSTRAINT SIS_PK PRIMARY KEY(SIS_CODE);

ALTER TABLE SMART_IN_ROOM
ADD CONSTRAINT SIR_PK PRIMARY KEY(SIR_SISCODE,SIR_CODE);

ALTER TABLE PAYMENT_HISTORY
ADD CONSTRAINT PH_PK PRIMARY KEY(PH_ACCOUNTID,PH_SIRSISCODE,PH_SIRCODE, PH_MBID);

ALTER TABLE GOALS_MEMBER
ADD CONSTRAINT GM_PK PRIMARY KEY(GM_PHACCOUNTID,GM_PHSIRSISCODE,GM_PHSIRCODE,GM_PHMBID);

ALTER TABLE HISTORY
ADD CONSTRAINT HI_PK PRIMARY KEY(HI_MBSIRSISCODE,HI_MBID, HI_DATE);

ALTER TABLE STATUS
ADD CONSTRAINT ST_PK PRIMARY KEY(ST_CODE);

ALTER TABLE DUST_SENSOR
ADD CONSTRAINT DUST_PK PRIMARY KEY(SE_SIRSISCODE, SE_SIRCODE, SE_CODE, SE_DATE);

ALTER TABLE DHT_SENSOR
ADD CONSTRAINT DHT_PK PRIMARY KEY(SE_SIRSISCODE, SE_SIRCODE, SE_CODE, SE_DATE);

ALTER TABLE LIGHT_SENSOR
ADD CONSTRAINT LIGHT_PK PRIMARY KEY(SE_SIRSISCODE, SE_SIRCODE, SE_CODE, SE_DATE);

ALTER TABLE RFID_SENSOR
ADD CONSTRAINT RFID_PK PRIMARY KEY(SE_SIRSISCODE, SE_SIRCODE, SE_CODE, SE_DATE);

ALTER TABLE HIR_SENSOR
ADD CONSTRAINT HIR_PK PRIMARY KEY(SE_SIRSISCODE, SE_SIRCODE, SE_CODE, SE_DATE);

ALTER TABLE IR_SENSOR
ADD CONSTRAINT IR_PK PRIMARY KEY(SE_SIRSISCODE, SE_SIRCODE, SE_CODE, SE_DATE);

ALTER TABLE SOUND_SENSOR
ADD CONSTRAINT SOUND_PK PRIMARY KEY(SE_SIRSISCODE, SE_SIRCODE, SE_CODE, SE_DATE);

ALTER TABLE REQUEST_SERVICE
ADD CONSTRAINT RS_PK PRIMARY KEY(RS_NAME, RS_PHONENUMBER,RS_ADDRESS);

/* SET FOREIGN KEY */
ALTER TABLE MEMBER
ADD CONSTRAINT MB_FK
FOREIGN KEY (MB_SIRSISCODE,MB_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE, SIR_CODE);
ALTER TABLE MEMBER
ADD CONSTRAINT MB_FK2
FOREIGN KEY (MB_STCODE) REFERENCES STATUS(ST_CODE);

ALTER TABLE GOALS_MEMBER
ADD CONSTRAINT GM_FK
FOREIGN KEY (GM_PHACCOUNTID, GM_PHSIRSISCODE, GM_PHSIRCODE, GM_PHMBID)
REFERENCES PAYMENT_HISTORY(PH_ACCOUNTID,PH_SIRSISCODE,PH_SIRCODE, PH_MBID);

ALTER TABLE PAYMENT_HISTORY
ADD CONSTRAINT PH_FK
FOREIGN KEY (PH_SIRSISCODE, PH_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE, SIR_CODE);
ALTER TABLE PAYMENT_HISTORY
ADD CONSTRAINT PH_FK2
FOREIGN KEY (PH_MBID, PH_SIRSISCODE) REFERENCES MEMBER(MB_ID, MB_SIRSISCODE);

ALTER TABLE HISTORY
ADD CONSTRAINT HI_FK
FOREIGN KEY (HI_MBID,HI_MBSIRSISCODE) REFERENCES MEMBER(MB_ID, MB_SIRSISCODE);
ALTER TABLE HISTORY
ADD CONSTRAINT HI_FK2
FOREIGN KEY (HI_STCODE) REFERENCES STATUS(ST_CODE);

ALTER TABLE SMART_IN_ROOM
ADD CONSTRAINT SIR_FK
FOREIGN KEY (SIR_SISCODE) REFERENCES SMART_IN_STUDY(SIS_CODE);

ALTER TABLE DUST_SENSOR
ADD CONSTRAINT DUST_FK
FOREIGN KEY (SE_SIRSISCODE, SE_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE,SIR_CODE);

ALTER TABLE DHT_SENSOR
ADD CONSTRAINT DHT_FK
FOREIGN KEY (SE_SIRSISCODE, SE_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE,SIR_CODE);

ALTER TABLE LIGHT_SENSOR
ADD CONSTRAINT LIGHT_FK
FOREIGN KEY (SE_SIRSISCODE, SE_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE,SIR_CODE);

ALTER TABLE RFID_SENSOR
ADD CONSTRAINT RFID_FK
FOREIGN KEY (SE_SIRSISCODE, SE_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE,SIR_CODE);

ALTER TABLE HIR_SENSOR
ADD CONSTRAINT HIR_FK
FOREIGN KEY (SE_SIRSISCODE, SE_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE,SIR_CODE);

ALTER TABLE IR_SENSOR
ADD CONSTRAINT IR_FK
FOREIGN KEY (SE_SIRSISCODE, SE_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE,SIR_CODE);

ALTER TABLE SOUND_SENSOR
ADD CONSTRAINT SOUND_FK
FOREIGN KEY (SE_SIRSISCODE, SE_SIRCODE) REFERENCES SMART_IN_ROOM(SIR_SISCODE,SIR_CODE);

ALTER TABLE REQUEST_SERVICE
ADD CONSTRAINT RS_FK
FOREIGN KEY (RS_STCODE) REFERENCES STATUS(ST_CODE);

/ SET SYNONYM /
CREATE SYNONYM MB FOR MEMBER;

CREATE SYNONYM GM FOR GOALS_MEMBER;

CREATE SYNONYM PH FOR PAYMENT_HISTORY;

CREATE SYNONYM HI FOR HISTORY;

CREATE SYNONYM ST FOR STATUS;

CREATE SYNONYM SIS FOR SMART_IN_STUDY;

CREATE SYNONYM SIR FOR SMART_IN_ROOM;

CREATE SYNONYM DUST FOR DUST_SENSOR;

CREATE SYNONYM DHT FOR DHT_SENSOR;

CREATE SYNONYM LIGHT FOR LIGHT_SENSOR;

CREATE SYNONYM RFID FOR RFID_SENSOR;

CREATE SYNONYM HIR FOR HIR_SENSOR;

CREATE SYNONYM IR FOR IR_SENSOR;

CREATE SYNONYM SOUND FOR SOUND_SENSOR;

CREATE SYNONYM RS FOR REQUEST_SERVICE;

commit;